//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fashion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int Product_ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> Category_ID { get; set; }
        public Nullable<int> Brand_ID { get; set; }
        public string Description { get; set; }
        public Nullable<bool> HotProduct { get; set; }
        public string Image { get; set; }
        public Nullable<int> Price { get; set; }
        public string content { get; set; }
        public Nullable<bool> BestSellingProducts { get; set; }
    }
}
